### ISSUE TITLE
Add the app to GitHub pages

### ISSUE THREAD

**Issue by imrans110** [abbas-13/first-react-project#8]
You can put your built app on github pages so that anyone can access publicly. 

You can automate the deployment process to GitHub Pages whenever there's a merge in the main branch by using GitHub Actions. GitHub Actions allows you to define custom workflows that run in response to specific events, such as a push or pull request.

To automate the deployment process, you can create a GitHub Actions workflow that triggers on a merge to the main branch and performs the necessary steps to deploy your React application to GitHub Pages. Here's an example workflow:

- In your repository, create a new directory called .github/workflows.

- Inside the .github/workflows directory, create a YAML file (e.g., deploy.yml) to define your workflow.

- Edit the deploy.yml file and add the following content:

```yaml
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: build
```

This workflow specifies that it should trigger on a push event to the main branch. It checks out the code, sets up Node.js, installs dependencies, builds the React application, and uses the github-pages-deploy-action to deploy the build folder to the gh-pages branch.

- Commit and push the deploy.yml file to your repository.

With this workflow in place, every time there is a merge into the main branch, the workflow will automatically run, triggering the deployment process to GitHub Pages.
